### ISSUE TITLE
Input values are filling concurrently

### ISSUE THREAD

**Issue by jitesh-sidhani** [azamat-cto/responsive-raveli-website#2]
In the contact page , input values are filling concurrently. 
![pick1](https://github.com/azamat-cto/responsive-raveli-website/assets/110370070/4a52d4e7-0cb3-4c5d-a508-bdf08580ccef)

**Comment by azamat-cto** [comment]
Fixed thanks a lot

**Comment by jitesh-sidhani** [comment]
It is not yet fixed . I would like to work on this . Please assign me this issue.

**Comment by jitesh-sidhani** [comment]
I have made changes in SendMessageForm.jsx . This issue is resolved.
![image](https://github.com/azamat-cto/responsive-raveli-website/assets/110370070/47e75dfb-528b-485b-a067-ce4785686d6e)

**Comment by azamat-cto** [comment]
how can i assign this issue for u 
sorry i do not very well with github settings

**Comment by azamat-cto** [comment]
I assigned u @jitesh-sidhani

**Comment by jitesh-sidhani** [comment]
I have send you Pull request . You can merge my Pull request & your file will be updated.

**Comment by azamat-cto** [comment]
ok thanks! I merged it
